# Generated by Django 2.2.8 on 2019-12-11 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flor',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floreria.Estado')),
            ],
        ),
    ]
