# Generated by Django 2.2.8 on 2019-12-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flor',
            name='imagen',
            field=models.ImageField(null=True, upload_to='flores'),
        ),
    ]
